version: '2'

checks:
    file-lines:
        config:
            threshold: 300
    method-lines:
        config:
            threshold: 50

exclude_patterns:
    - 'config/'
    - 'db/'
    - 'dist/'
    - 'features/'
    - '**/node_modules/'
    - 'script/'
    - '**/spec/'
    - '**/test/'
    - '**/tests/'
    - 'Tests/'
    - '**/vendor/'
    - '**/*_test.go'
    - '**/*.d.ts'
    - '**/*.spec.ts'
    - '**/*.json'
    - '**/*.yml'
    - '**/routes.ts'
    - '.nyc_output/'
    - 'coverage/'
    - 'resources/'
    - '.eslintignore'
    - '.eslintrc'
    - '.gitignore'
    - '.prettierignore'
    - '**/Dockerfile'
    - 'LICENSE'
    - 'README.md'
