version: '3.8'

services:
    mongodb:
        image: mongo
        restart: always
        env_file:
            - '.env'
        environment:
            MONGO_INITDB_ROOT_USERNAME: '${MONGODB_USERNAME}'
            MONGO_INITDB_ROOT_PASSWORD: '${MONGODB_PASSWORD}'
        ports:
            - '${MONGODB_PORT}:27017'
        volumes:
            - mongodb_data:/data/db

volumes:
    mongodb_data:
